### ISSUE TITLE
Missing Buttons

### ISSUE THREAD

**Issue by henfri** [rampage128/hombot-interface#1]
Hello Frederik,

thanks for this great User Interface.
The update worked flawlessly (via scp) and I really like the Interface
What I am missing though is the buttons
-Home
-Pause
-Start

It would be great, if you could add them.

Greetings,
Hendrik

**Comment by rampage128** [comment]
Controls added with commit 66e07d21797ed4b7716d675fb46c916bf8a1d308.
Fix will be rolled out with the next release aswell.

**Comment by henfri** [comment]
Thanks!
