### ISSUE TITLE
Link to old WebInterface

### ISSUE THREAD

**Issue by henfri** [rampage128/hombot-interface#2]
Hello,

when copying the files to my bot, I did not have the impression, that I overwrote files.
So, the old webinterface should still be there, right?

Would it be possible to link to the old webinterface for backward-compatibility? I am thinking about missing features like being able to upload files, checking the version of the server etc. Usually, in the forum Screenshots of the old interface are shown.

Greetings,
Hendrik

**Comment by rampage128** [comment]
Technically it is not overwriting. But the way lg.srv handles the situation is as follows:
- user sends request to a file
- if file exists in `htdocs`, then lg.srv delivers the file and that's it
- if file does not exist in `htdocs`, lg.srv delivers the packaged file

Thus it is not possible to open "legacy" pages which exist with the same name in `htdocs`. The only file which should be affected is `index.html` as this is inevitable.

The only page not functioning properly at the moment (in master) is the `sites/service.html`, which can directly be opened in the browser.

For the next release I will try to fix the service tab. If not possible, I will add a link to the legacy service page.

**Comment by rampage128** [comment]
Link added with 0046d2e3a95ea471dcb81cb4e872af17be8c91f7
